import { chromium } from 'playwright';
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const browser = await chromium.launch({ headless:true });
const errors=[];
const P = await browser.newPage({viewport:{width:1600,height:900}});
P.on('pageerror', e=>errors.push(e.message));
await P.goto('http://localhost:4001');
await P.fill('#name-input','房主');
await P.click('#create-room-btn');
await sleep(800);
const code = await P.inputValue('#room-input');
console.log('创建房间码=' + code);
const settingsVisible = await P.isVisible('#room-settings');
console.log('设置面板可见=' + settingsVisible);
await P.selectOption('#set-map','classic');
await sleep(400);
await P.click('#add-ai-btn');
await sleep(400);
await P.click('#start-btn');
await sleep(1500);
const inGame = await P.$eval('#game', el => !el.classList.contains('hidden'));
const hasCanvas = await P.$('#board canvas') !== null;
console.log('进入游戏=' + inGame + ' 棋盘canvas=' + hasCanvas + ' errors=' + JSON.stringify(errors));
await browser.close();